<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    tip
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
    $meta = $this->getData('meta');

    if (!$meta instanceof AW_Blog_Helper_Data && $meta->getAddress()) {
        $canonicalUrl = $meta->getAddress();
    } else {
        $canonicalUrl = Mage::helper('core/url')->getCurrentUrl();
    }

    $logoSrc = Mage::getStoreConfig('design/header/logo_src');

    if (Mage::getStoreConfig('blog/blog/image_meta')) {
        $imageurl = Mage::getBaseUrl('media') . 'blog' . DS . Mage::getStoreConfig('blog/blog/image_meta');
    } else {
        $imageurl = $this->getSkinUrl($logoSrc);
    }
?>

<!-- Open Graph data -->
<meta property="og:title" content="<?php echo $meta->getTitle() ?>" />
<meta property="og:type" content="article" />
<meta property="og:description" content="<?php echo $meta->getMetaDescription() ?>" />
<meta property="og:image" content="<?php echo $imageurl ?>" />
<meta property="og:image:width" content="250" />
<meta property="og:image:height" content="250" />
<meta property="og:url" content= "<?php echo $canonicalUrl ?>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="<?php echo $meta->getTitle() ?>" />
<meta name="twitter:description" content="<?php echo $meta->getMetaDescription() ?>" />
<meta name="twitter:url" content="<?php echo $canonicalUrl ?>" />
<meta name="twitter:image" content="<?php echo $imageurl ?>" />
