<div class="social-footer">
<!-- If you want to remove this, please purchase "Remove powered by" package at https://magegiant.com/ -->
	<a href="https://magegiant.com/magento-social-login-extension/" target="_blank" rel="copyright">Social Login</a> 
	<span>Powered by</span>
	<a href="https://magegiant.com/" target="_blank" rel="copyright">Magegiant</a> and 
	<a href="https://magegiant.com/magento-reward-points-extension/" title="Magento Reward Points loyalty program">Reward Points</a>
	<a href="https://magegiant.com/magento-one-step-checkout/" title="Magento one step checkout 2">One step checkout</a>
</div>

<style>
    .social-footer, .social-footer a, .social-footer a:social-footer, .social-footer a:visited{ font-size: 0.6em !important; color: #ccc !important; }
</style>
