<?php
$_configColors = Mage::getStoreConfig('milanoconfig/colors');
$_configBackground = Mage::getStoreConfig('milanoconfig/background');
$_configFonts = Mage::getStoreConfig('milanoconfig/fonts');

$_primary_color = $_configColors['primary_color'];
$_primary_hover = $_configColors['primary_hover'];

$_secondary_color = $_configColors['secondary_color'];
$_secondary_hover = $_configColors['secondary_hover'];

$_pattern = $_configBackground['pattern'];
$_main_color = $_configBackground['maincolor'];
$_bg_repeat = $_configBackground['bg_repeat'];
$_bg_attachment = $_configBackground['bg_attachment'];
$_bg_position_x = $_configBackground['bg_position_x'];
$_bg_position_y = $_configBackground['bg_position_y'];

$_primary_font = $_configFonts['primary_font'];
$_secondary_font = $_configFonts['secondary_font'];

if(!empty($_primary_font)): 
$_primary_font_name = explode(":",$_primary_font);
$_primary_font_name = str_replace("+"," ", $_primary_font_name[0]);

?><link href='http://fonts.googleapis.com/css?family=<?php echo($_primary_font); ?>' rel='stylesheet' type='text/css'><?php endif;
if(!empty($_secondary_font)): 
$_secondary_font_name = explode(":",$_secondary_font);
$_secondary_font_name = str_replace("+"," ", $_secondary_font_name[0]);

?><link href='http://fonts.googleapis.com/css?family=<?php echo($_secondary_font); ?>' rel='stylesheet' type='text/css'><?php endif;

$selectors = Array();
$selectors['active_color'] = '
button.btn-checkout,
.breadcrumbs li strong,
.header .welcome-msg,
#nav li.level0.active > a > span,
#tweets a,
.products-grid li.item a.btn-cart,
.products-grid .availability.out-of-stock span,
.products-grid .add-to-links li a,
.products-list li.item a.btn-cart,
.products-list .desc a,
#added a,
.product-view .product-shop .short-description a,
.product-view .product-shop .availability.in-stock span,
.product_label,
.add-to-cart button.button,
.product-view .box-tags .form-add button.button > span,
.product-tabs li.active a,
.sp-methods .price,
button.btn-checkout,
.new-arrow.prev:active,
.new-arrow.next:active,
.sale-arrow.prev:active,
.sale-arrow.next:active,
.brands-arrow.prev:active,
.brands-arrow.next:active
';

$selectors['active_color_hover'] = '
.footer-container .follow-us a:hover,
.products-grid .add-to-links li a:hover,
.products-grid li.item.boxed:hover,
.product-tabs li:hover a,
#nav li.level0 > a:hover > span,
.new-arrow.prev:hover, .new-arrow.prev:focus, .new-arrow.next:hover, .new-arrow.next:focus, .sale-arrow.prev:hover, .sale-arrow.prev:focus, .sale-arrow.next:hover, .sale-arrow.next:focus, .brands-arrow.prev:hover, .brands-arrow.prev:focus, .brands-arrow.next:hover, .brands-arrow.next:focus
';

$selectors['active_color3'] = '
';

$selectors['active_bg'] = '
';

$selectors['active_bg2'] = '
';

$selectors['active_border'] = '
input.input-text:focus,textarea:focus,
button.btn-checkout,
.success-msg,
#nav,
.products-grid li .addto,
.products-list li.item a.btn-cart,
#added a,
.add-to-cart button.button,
.product-tabs,
.product-tabs li.active a,
input.input-text:focus,textarea:focus,
button.btn-checkout
';

$selectors['dark_color'] = '
.product_label.sale,
.special-price .price
';

$selectors['dark_bg'] = '
';

$selectors['dark_color_hover'] = '
';

$selectors['dark_bg_hover'] = '
';

$selectors['primary_font_normal'] = '
.header-menu > ul > li > a,
.cart-header .button-show a,
.cart-header .price,
.block-compare-header .button-show a,
.header .links li a,
.header-promo-container .header-left,
ul.home-callout,
#added a,
.block .block-title strong span
';

$selectors['primary_font_book'] = '
h1,h2,h3,h4,h5,h6,
.header-small-container,
#tweets .user a,
.products-list .product-name,
.product-view .product-shop .short-description p:first-child,
.product-options dt label,
#product_tabs_description_contents h2,
#mobile-menu-button,
#mobile-menu li.level0 > a > span
';

$selectors['primary_font_semibold'] = '
input.qty,
button.button,
.validation-advice,
.messages,
.breadcrumbs,
.data-table,
.block-compare-header .clear-all,
#nav li.level0 > a > span,
#nav li.level0 > p > a > span,
#nav .nav_block li.parent > a > span,
#nav li.level1 > a > span,
#nav .nav_block h3,
#nav li.nav-text-block h3,
.footer-container h4,
.products-list li.item a.btn-cart,
.products-list li.item a.btn-quickview,
.product-view .product-shop .product-code,
.product-view .product-shop .availability,
.product-view .product-shop .countdown-timer h5,
.add-to-cart label,
.product-options select,
.product-tabs li a,
.product-tabs-content,
.product-tabs-content .data-table th,
.product-tabs-content .form-list label,
.product-accordion dt a,
.cart-table .product-name,
.cart .discount h2,
.cart .shipping h2,
.opc .step-title h2,
.dashboard .welcome-msg p.hello,
.dashboard .box .box-title h3,
.dashboard .box .box-title h4,
.dashboard .box-reviews .box-head h2,
.dashboard .box-tags .box-head h2,
#mobile-menu li.level1 a span
';

$selectors['primary_font_bold'] = '
button.btn-checkout span,
.inline-layers dt,
.inline-layers .currently ol li,
.inline-layers .currently .actions,
.category-products li.item button.button,
.category-products li.item .availability span,
.category-products li.item a.btn-cart,
.products-list .add-to-links li a,
.quantity_box_button_up,
.quantity_box_button_down,
.product-view .product-shop .add-to-links li a,
.add-to-cart button.button span,
.checkout-cart-index .cross-sale-container .btn-cart
';

$selectors['secondary_font'] = '
body,
.footer-color .follow_us,
.block .block-title strong span,
.product-tabs li,
.footer-color .phone span,
.product-view .product-shop .short-description p:first-child,
.add-to-cart label,
.newproduct_grid,
.saleproduct,
.price,
input,select,textarea,button,
.header .currency .currency-menu-item a,
.header .form-language .form-language-item a,
.header .store-switcher .store-switcher-item a,
.header-menu > ul > li > ul a,
.cart-header #header-items,
.cart-header #header-items.empty,
.block-compare-header #header-items,
.block-compare-header #header-items.empty,
#nav ul.level1,
.footer-container,
.footer-container a,
.home-text h3,
a.readmore,
.postTitle h6,
.product-slider .new-description h3,
.products-grid .product-name,
.products-list .desc,
#added #added-content,
.ajax-message,
.block-related .product-details .product-name,
.product-view .product-shop .short-description,
.mini-products-grid .product-name,
#wishlist-table .description
';
if(!empty($_primary_color) || !empty($_primary_hover) || !empty($_secondary_color) || !empty($_secondary_color_hover) || !empty($_main_color) || !empty($_pattern) || !empty($_primary_font) || !empty($_secondary_font)): ?>
<style type="text/css"><?php
	if(!empty($selectors['active_color']) && !empty($_primary_color)):
	echo $this->jsString($selectors['active_color']); ?>{ color: <?php echo $_primary_color ?>; } <?php endif;
	
	if(!empty($selectors['active_color_hover']) && !empty($_primary_hover)):
	echo $this->jsString($selectors['active_color_hover']); ?>{ color: <?php echo $_primary_hover ?>; } <?php endif;
	
	if(!empty($selectors['active_color3']) && !empty($_primary_color)):
	echo $this->jsString($selectors['active_color3']); ?>{ border-left-color: <?php echo $_primary_color ?>; } <?php endif;
	
	if(!empty($selectors['active_bg']) && !empty($_primary_color)):
	echo $this->jsString($selectors['active_bg']); ?>{ background-color: <?php echo $_primary_color ?>; } <?php endif;
	
	if(!empty($selectors['active_bg2']) && !empty($_primary_hover)):
    echo $this->jsString($selectors['active_bg2']); ?>{ background-color: <?php echo $_primary_hover ?>; text-decoration: underline; } <?php endif;
	
	if(!empty($selectors['active_border']) && !empty($_primary_color)):
    echo $this->jsString($selectors['active_border']); ?>{ border-color: <?php echo $_primary_color ?>; } <?php endif;
	
	if(!empty($selectors['dark_color']) && !empty($_secondary_color)):
    echo $this->jsString($selectors['dark_color']); ?>{ color: <?php echo $_secondary_color ?>; } <?php endif;
	
	if(!empty($selectors['dark_bg']) && !empty($_secondary_color)):
    echo $this->jsString($selectors['dark_bg']); ?>{ background-color: <?php echo $_secondary_color ?>; } <?php endif;
	
	if(!empty($selectors['dark_color_hover']) && !empty($_secondary_color_hover)):
	echo $this->jsString($selectors['dark_color_hover']); ?>{ color: <?php echo $_secondary_color_hover ?>; } <?php endif;
	
	if(!empty($selectors['dark_bg_hover']) && !empty($_secondary_color_hover)):
    echo $this->jsString($selectors['dark_bg_hover']); ?>{ background-color: <?php echo $_secondary_color_hover ?>; } <?php endif;
		
	if(!empty($_primary_color)):
	?> ::-moz-selection { background-color: <?php echo $_primary_color ?>; } ::selection { background-color: <?php echo $_primary_color ?>; } <?php endif;
	if(!empty($_main_color) || !empty($_pattern)): 
	?> body{ background-color: <?php echo $_main_color ?>; background-attachment: <?php echo $_bg_attachment ?>; background-position: <?php echo $_bg_position_y ?> <?php echo $_bg_position_x ?>; background-repeat: <?php echo $_bg_repeat ?>; <?php if($_pattern && $_pattern != ''): ?>background-image: url(<?php echo Mage::registry('themeMediaUrl').$_pattern ?>);<?php endif; ?> } <?php endif; 
	
	if(!empty($_primary_font)):
	echo $this->jsString($selectors['primary_font_normal']); ?> { font-family: '<?php echo($_primary_font_name); ?>'; text-transform: uppercase; } <?php
	echo $this->jsString($selectors['primary_font_book']); ?> { font-family: '<?php echo($_primary_font_name); ?>'; font-weight: 300; text-transform: uppercase; } <?php
	echo $this->jsString($selectors['primary_font_semibold']); ?> { font-family: '<?php echo($_primary_font_name); ?>'; font-weight: 600; text-transform: uppercase; } <?php
	echo $this->jsString($selectors['primary_font_bold']); ?> { font-family: '<?php echo($_primary_font_name); ?>'; font-weight: 700; text-transform: uppercase; } <?php endif;
	
	if(!empty($_secondary_font)):
	echo $this->jsString($selectors['secondary_font']); ?> { font-family: '<?php echo($_secondary_font_name); ?>'; } <?php endif
	
	?>
</style>
<?php endif; ?>
<script type="text/javascript">
	var BASE_URL = '<?php  echo $this->getBaseUrl(); ?>';
	var CUSTOM_LINK_URL = '<?php echo Mage::getStoreConfig('milanoconfig/menuoptions/additional_nav_href'); ?>';  
</script>