<?php
/**
 * @var $this IWD_Opc_Block_Onepage_Review_Renderer_Storecredit
 */

?>
<?php if ($this->getTotal()->getValue()) { ?>
    <div class="iwd_opc_top_review_total">
        <div class="iwd_opc_top_review_total_cell">
            <?php echo $this->escapeHtml($this->__('Store Credit')) . ':'; ?>
        </div>
        <div class="iwd_opc_top_review_total_cell">
            <?php echo $this->escapeHtml($this->getStoreCreditPrice()); ?>
        </div>
    </div>
<?php } ?>


