<!-- my Short Cart Logo -->
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/myshortcart/logo.png' ?>" alt="<?php echo Mage::helper('myshortcart')->__('myShortCart Logo') ?>" class="v-middle" />&nbsp;
<a href="<?php echo Mage::getBaseUrl().'myshortcart/whatismyshortcart'?>" onclick="javascript:window.open('<?php echo Mage::getBaseUrl().'myshortcart/whatismyshortcart'?>','olcwhatispaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=400, height=350'); return false;"><?php echo Mage::helper('myshortcart')->__('Apa itu myShortCart?') ?></a>
<!-- paypal Logo -->
