<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('myshortcart')->__('Konfirmasi Pembayaran myshortcart') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="myshortcartForm" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('myshortcart')->__('Harap masukkan detail pembayaran myshortcart!') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Nama') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('myshortcart')->__('Nama') ?>" value="<?php echo $this->htmlEscape($this->helper('myshortcart')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('myshortcart')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('myshortcart')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Telephone/HP') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('myshortcart')->__('Telephone/HP') ?>" value="" class="required-entry input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="order_id" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Order ID') ?></label>
                <div class="input-box">
                    <input name="order_id" id="order_id" title="<?php echo Mage::helper('myshortcart')->__('Order ID') ?>" value="" class="required-entry input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="transaction_id" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Transaksi ID myshortcart') ?></label>
                <div class="input-box">
                    <input name="transaction_id" id="transaction_id" title="<?php echo Mage::helper('myshortcart')->__('Transaksi ID myshortcart') ?>" value="" class="required-entry input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="transfer_date" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Tanggal Transfer') ?></label>
                <div class="input-box">
                    <input name="transfer_date" id="transfer_date" title="<?php echo Mage::helper('myshortcart')->__('Tanggal Transfer') ?>" value="" class="required-entry input-text" type="text" />
                </div>
            </li>
            <li>
                <label for="amount_transfered" class="required"><em>*</em><?php echo Mage::helper('myshortcart')->__('Jumlah Transfer') ?></label>
                <div class="input-box">
                    <input name="amount_transfered" id="amount_transfered" title="<?php echo Mage::helper('myshortcart')->__('Jumlah Transfer') ?>" value="" class="required-entry input-text" type="text" />
                </div>
            </li>
            <li class="wide">
                <label for="comment"><?php echo Mage::helper('myshortcart')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('myshortcart')->__('Comment') ?>" class="input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('myshortcart')->__('* Harus diisi') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('myshortcart')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('myshortcart')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var myshortcartForm = new VarienForm('myshortcartForm', true);
//]]>
</script>
