<?php
/**
 * @var $this Gene_Braintree_Block_Paypal
 */
?>
<?php echo $this->getSavedChildHtml(); ?>
<div class="paypal-info"
    <?php if ($this->hasSavedDetails() && $this->getMethod()->isVaultEnabled()) { ?>
        style="display: none;"
    <?php } ?>>
    <div class="iwd_opc_universal_wrapper">
        <div class="iwd_opc_paypal_redirect_icon"></div>
    </div>
    <div class="iwd_opc_universal_wrapper">
        <?php echo $this->escapeHtml(
            $this->__('After clicking "Place Order", you will be directed to enter your payment credentials.')
        ); ?>
    </div>
    <?php if ($this->canSavePayPal()): ?>
        <div class="iwd_opc_universal_wrapper">
            <label title="<?php echo $this->escapeHtml(
                $this->__('Save this account for future use')
            ); ?>"
                   class="iwd_opc_checkbox_label"
                   for="gene_braintree_paypal_store_in_vault">
                <input type="checkbox"
                       id="gene_braintree_paypal_store_in_vault"
                       value="1"
                       name="payment[save_paypal]"
                       class="iwd_opc_checkbox iwd_opc_field"/>
                <span class="iwd_opc_checkbox_label_value">
                <?php echo $this->escapeHtml(
                    $this->__('Save this account for future use')
                ); ?>
            </span>
            </label>
        </div>
    <?php endif; ?>
    <input type="hidden" name="payment[payment_method_nonce]" id="paypal-payment-nonce"/>
</div>
<!-- Attach an event onto all radio buttons -->
<script type="text/javascript">
    // Set a flag to determine whether the PayPal flag is initialized
    var PayPalInit = false;
    // Wrap our logic in a function so we can init in different ways
    initPayPal = function () {
        // Verify that vzero is defined before attempting to use it
        if (typeof vzeroPaypal !== 'undefined') {
            // Yay we're good to go
            PayPalInit = true;
            // Always set the amount as it's needed within 3D secure requests
            vzeroPaypal.setPricing(
                '<?php echo Mage::helper('gene_braintree')->formatPrice(
                        Mage::getSingleton('checkout/cart')->getQuote()->collectTotals()->getGrandTotal()
                ); ?>',
                '<?php echo Mage::getSingleton('checkout/cart')->getQuote()->getQuoteCurrencyCode(); ?>'
            );
        }

        if (typeof vzero !== 'undefined') {
            vzero.paypalLoaded();
        }
    };
    // Init PayPal on load
    initPayPal();
    // If the function didn't run on the load of the payment method do it on dom:loaded
    if (!PayPalInit) {
        document.observe('dom:loaded', function () {
            initPayPal();
        });
    }
</script>