<h2>Terima Kasih</h2>

<div class="awbali_formwrapper">
	<p>Terima Kasih atas konfirmasi pembayaran Anda. Kami akan melakukan pengecekan terlebih dahulu.<br />
	Jika Anda mempunyai pertanyaan mengenai order Anda, silakan menghubungi Customer Support Kami melalui SMS/WA di +62813 2297 6000 | +62811 2181 600 atau e-Mail di <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_support/email');?>"><?php echo Mage::getStoreConfig('trans_email/ident_support/email');?></a></p>
</div>
