<div id="co-billing-form">
	<h3><?php echo $this->__('Name & Address')?></h3>
	<ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
		<li class="wide">
			<label for="billing-address-select" class="notice"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
			<div class="input-box">
				<?php echo $this->getAddressesHtmlSelect('billing') ?>
			</div>
		</li>
    <?php endif; ?>
    <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
			<fieldset>
				<input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
				<ul>
					<li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
					<div class="clear"></div>
					<li class="fields">
						<div class="field">
							<label for="billing:company"><?php echo $this->__('Company') ?></label>
							<div class="input-box">
								<input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('company') ?>" />
							</div>
						</div>
						<?php if(!$this->isCustomerLoggedIn()): ?>
						<div class="field">
							<label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
							<div class="input-box">
								<input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
							</div>
						</div>
						<?php endif; ?>
					</li>
					<div class="clear"></div>
					<?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>
					<li class="wide">
						<label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
						<div class="input-box">
							<input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
						</div>
					</li>
					<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
					
					<?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
					<li class="wide">
						<label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
						<div class="input-box">
							<input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
						</div>
					</li>
					<?php endif; ?>
					<li class="wide">
						<div class="field">
							<label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
							<div class="input-box">
								<?php echo $this->getCountryHtmlSelect('billing') ?>
							</div>
						</div>
					</li>
					<li class="wide">
						<div class="field">
							<label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
							<div class="input-box">
								<select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
									<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
								</select>
								<script type="text/javascript">
									//<![CDATA[
									$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
									//]]>
								</script>
								<input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
							</div>
						</div>
					</li>
					<li class="wide">
						<div class="field">
							<label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
							<div class="input-box">
								<input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="billing:city" style="display:none;" />
								
								<select id="skabkota" class="validate-select com-box" >
									<option>Pilih Kota</option>
								</select>
							</div>
						</div>
					</li>
					<?php 
						//for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): 
						$_i = 2;
					?>
					<li class="wide">
						<label for="billing:city" class="required"><em>*</em><?php echo $this->__('Kecamatan') ?></label>
						<div class="input-box">
							<input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" style="display:none;" />
							<select id="skec" class="validate-select com-box">
								<option>Pilih Kecamatan</option>
							</select>
						</div>
					</li>
					<?php 
						//endfor; 
					?>
					<li class="wide">
						<div class="field">
							<label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
							<div class="input-box">
								<input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
							</div>
						</div>
					</li>
					<li class="fields">
						<div class="field">
							<label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
							<div class="input-box">
								<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>" />
							</div>
						</div>
						<div class="field">
							<label for="billing:fax"><?php echo $this->__('Fax') ?></label>
							<div class="input-box">
								<input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
							</div>
						</div>
					</li>
					<?php if(!$this->isCustomerLoggedIn()): ?>
					
					<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
					<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
					<?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
					<li class="fields">
						<?php if ($_dob->isEnabled()): ?>
						<div class="field">
							<?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
						</div>
						<?php endif; ?>
						<?php if ($_gender->isEnabled()): ?>
						<div class="field">
							<?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
						</div>
						<?php endif ?>
					</li>
					<div class="clear"></div>
					<?php endif ?>
					
					<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
					<?php if ($_taxvat->isEnabled()): ?>
					<li>
						<?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
					</li>
					<?php endif ?>
					
					
					<?php endif; ?>
					<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
					<div class="clear"></div>
					<li class="control">
						<input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
					</li>
					<?php else:?>
					<li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
					<?php endif; ?>
					<?php echo $this->getChildHtml('form.additional.info'); ?>
				</ul>
			</fieldset>
		</li>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>
		
    <!-- fix browser autocomplete -->
		<div style="display:none !important">
			<input type="text" autocomplete="off" value="" />
			<input type="password" autocomplete="off" value=""/>
		</div>
		<!-- end fix browser autocomplete -->
    
    <?php if(!$this->isCustomerLoggedIn()): ?>
    
		<?php
    	$guest_allowed = $this->getQuote()->isAllowedGuestCheckout();
		if($guest_allowed): ?>
		<li class="control">
			<input type="checkbox" name="billing[create_account]" id="billing:create_account" value="1" title="<?php echo  $this->__('Create an account for later use') ?>"  class="checkbox" /><label for="billing:create_account"><?php echo  $this->__('Create an account for later use') ?></label>
		</li>
		<?php else:?>
		<input type="hidden" name="billing[create_account]" id="billing:create_account" value="1" />
		<?php endif;?>
		
		<li class="fields <?php if($guest_allowed):?>hidden<?php endif;?>" id="register-customer-password">
			<div class="field">
				<label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
				<div class="input-box">
					<input type="password" name="billing[customer_password]" title="<?php echo $this->__('Password') ?>" id="billing:customer_password" class="input-text validate-password <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off" value=""/>
				</div>
			</div>
			<div class="field">
				<label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
				<div class="input-box">
					<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text validate-cpassword <?php if(!$guest_allowed):?>required-entry<?php endif;?>" autocomplete="off" value=""/>
				</div>
			</div>
		</li>
		<div class="clear"></div>
    
    <?php endif;?>
    
    <?php if ($this->canShip()): ?>
		<li class="control <?php if (!Mage::helper('opc')->isShowShippingForm()):?>hidden<?php endif;?>">
			<input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1"<?php if ($this->isUseBillingAddressForShipping()) {?> checked="checked"<?php }?> title="<?php echo  $this->__('Ship to this address') ?>" class="checkbox   " /><label for="billing:use_for_shipping_yes"><?php echo  $this->__('Ship to this address') ?></label>
		</li>
    <?php endif; ?>
	</ul>
	<?php if (!$this->canShip()): ?>
	<input type="hidden" name="billing[use_for_shipping]" value="1" />
	<?php endif; ?>
	
</div>
<script type="text/javascript">
	//<![CDATA[
	document.observe("dom:loaded", function() {
		Element.addMethods("SELECT", (function() {
			function getSelectedOptionHTML(element) {
				if (!(element = $(element))) return;
				var index = element.selectedIndex;
				return index >= 0 ? element.options[index].innerHTML : undefined;
			}
			
			return {
				getSelectedOptionHTML: getSelectedOptionHTML
			};
		})());
		/*
			* Script created by Daeng
			* Jangan diedit, tanya dulu
		*/ 
		/**
			* Enable CORS for prototype.js and get rid of the message "Refused to get unsafe header X-JSON"
			* play with it: http://jsfiddle.net/Ajx2k/11/
			*
			* Created by Smiley <@codemasher> on 11.01.14.
			*/
			
			// Enable CORS for Prototype: http://kourge.net/node/131
			// With this, the console will still tell you: Refused to get unsafe header "X-JSON"
			Ajax.Responders.register({
				onCreate: function(response){
					var t = response.transport;
					//for PHPStorm's sake
					//noinspection FunctionWithInconsistentReturnsJS
					t.setRequestHeader = t.setRequestHeader.wrap(function(original, k, v){
						if(/^(accept|accept-language|content-language)$/i.test(k) ||
						(/^content-type$/i.test(k) && /^(application\/x-www-form-urlencoded|multipart\/form-data|text\/plain)(;.+)?$/i.test(v))){
							return original(k, v);
						}
						//for PHPStorm's sake
						//noinspection UnnecessaryReturnStatementJS
						return;
					});
				}
			});
			
			// So, then lets get rid of this nasty message
			// it is caused by _getHeaderJSON() which tries to receive this header
			
			// the long way if you want to keep the original methods
			
			// so let's override the original method in Ajax.Response
			// see: http://prototypejs.org/learn/class-inheritance
			Ajax.JSONResponse = Class.create(Ajax.Response, {
				_getHeaderJSON: Prototype.emptyFunction
			});
			
			// next, we need to replace all occurences of Ajax.Response with our new class Ajax.JSONResponse
			// this is kinda lazy but works fine - more elegant anyone?
			Ajax.JSON = Class.create(Ajax.Request, {
				request: function(url) {
					this.url = url;
					this.method = this.options.method;
					var params = Object.isString(this.options.parameters) ?
					this.options.parameters :
					Object.toQueryString(this.options.parameters);
					
					if (!['get', 'post'].include(this.method)) {
						params += (params ? '&' : '') + "_method=" + this.method;
						this.method = 'post';
					}
					
					if (params && this.method === 'get') {
						this.url += (this.url.include('?') ? '&' : '?') + params;
					}
					
					this.parameters = params.toQueryParams();
					
					try {
						var response = new Ajax.JSONResponse(this);
						if (this.options.onCreate) this.options.onCreate(response);
						Ajax.Responders.dispatch('onCreate', this, response);
						
						this.transport.open(this.method.toUpperCase(), this.url,
						this.options.asynchronous);
						
						if (this.options.asynchronous) this.respondToReadyState.bind(this).defer(1);
						
						this.transport.onreadystatechange = this.onStateChange.bind(this);
						this.setRequestHeaders();
						
						this.body = this.method == 'post' ? (this.options.postBody || params) : null;
						this.transport.send(this.body);
						
						/* Force Firefox to handle ready state 4 for synchronous requests */
						if (!this.options.asynchronous && this.transport.overrideMimeType)
						this.onStateChange();
						
					}
					catch (e) {
						this.dispatchException(e);
					}
				},
				
				respondToReadyState: function(readyState) {
					var state = Ajax.Request.Events[readyState], response = new Ajax.JSONResponse(this);
					
					if (state == 'Complete') {
						try {
							this._complete = true;
							(this.options['on' + response.status]
							|| this.options['on' + (this.success() ? 'Success' : 'Failure')]
							|| Prototype.emptyFunction)(response, response.headerJSON);
							} catch (e) {
							this.dispatchException(e);
						}
						
						var contentType = response.getHeader('Content-type');
						if (this.options.evalJS == 'force'
						|| (this.options.evalJS && this.isSameOrigin() && contentType
						&& contentType.match(/^\s*(text|application)\/(x-)?(java|ecma)script(;.*)?\s*$/i)))
						this.evalResponse();
					}
					
					try {
						(this.options['on' + state] || Prototype.emptyFunction)(response, response.headerJSON);
						Ajax.Responders.dispatch('on' + state, this, response, response.headerJSON);
						} catch (e) {
						this.dispatchException(e);
					}
					
					if (state == 'Complete') {
						this.transport.onreadystatechange = Prototype.emptyFunction;
					}
				}
			});
			
			
			// TL;DR: the short and nasty way:
			Ajax.Response.prototype._getHeaderJSON = Prototype.emptyFunction;
			
			
			// ok, lets test it
			
			// native Ajax.Request
			var $AJAX = function(url, fn){
				new Ajax.Request(url, {
					method: 'get',
					onSuccess: function(r){
						fn(r.responseJSON);
					}
				});
			};
			
			// our new Ajax.JSON
			var $JSON = function(url, fn){
				new Ajax.JSON(url, {
					method: 'get',
					onSuccess: function(r){
						fn(r.responseJSON);
					}
				});
			};
			
			
		});
		//]]>
	</script>
	<script type="text/javascript">
		//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
		var jq = jQuery.noConflict();
		var GantiKec = Class.create({
			handleClick: function(event) {
				event.stop();
				$('billing:postcode').setValue("");
				//$$('dl.shipment-methods')[0].innerHTML = '';
				$('billing:city').setValue($('skabkota').getValue());
				$('billing:street2').setValue($('skec').getValue());
				//applyShippingMethod('');
			},
			handleChange: function(event) {
				event.stop();
				opt = '<option value="">--pilih kecamatan--</option>';
				$('skec').innerHTML = opt;
				var y = $('skabkota').getValue();
				//var x = $('billing:region_id').getSelectedOptionHTML();
				var x = jq('#billing\\:region_id option:selected').text();
				//alert(x);
				new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kecamatan/?kabkota='+y+'&prop='+x,{
					onLoading: function(response){
						
					},
					onSuccess: function(response) {
						var opt = '';
						response.responseJSON.each(function(item){
							opt += '<option value="'+item+'">'+item+'</option>';
						});
						$('skec').innerHTML = opt;
						$('billing:street2').setValue($('skec').getValue());
						//applyShippingMethod('');
					}
				});
			}
		});
		
		var GantiKabKota = Class.create({
			handleClick: function(event) {
				$('billing:city').setValue($('skabkota').getValue());
			},
			handleChange: function(event) {
				event.stop();
				opt = '<option value="">--pilih kab/kota--</option>';
				$('skabkota').innerHTML = opt;
				opt = '<option value="">--pilih kecamatan--</option>';
				$('skec').innerHTML = opt;
				
				//var x = $('billing:region_id').getSelectedOptionHTML();
				var x = jq('#billing\\:region_id option:selected').text();
				//alert(x);
				new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kabkota/?prop='+x,{
					onLoading: function(response){
						
					},
					onSuccess: function(response) {
						var opt = '';
						response.responseJSON.each(function(item){
							opt += '<option value="'+item.nilai+'">'+item.nama+'</option>';
						});
						$('skabkota').innerHTML = opt;
						
						
						opt = '<option value="">--pilih kecamatan--</option>';
						$('skec').innerHTML = opt;
						var y = $('skabkota').getValue();
						var x = jq('#billing\\:region_id option:selected').text();
						//alert(x);
						new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kecamatan/?kabkota='+y+'&prop='+x,{
							onLoading: function(response){
								
							},
							onSuccess: function(response) {
								var opt = '';
								response.responseJSON.each(function(item){
									opt += '<option value="'+item+'">'+item+'</option>';
								});
								$('skec').innerHTML = opt;
								
								$('billing:street2').setValue($('skec').getValue());
								$('billing:city').setValue($('skabkota').getValue());
							}
						});
					}
				});
			}
		});
		
		var GantiNegara = Class.create({
			handleChange: function(event) {
				//opt = '<option value="">--Pilih Kab/Kota--</option>';
				//$('skabkota').innerHTML = opt;
				//opt = '<option value="">--Pilih Kecamatan--</option>';
				//$('skec').innerHTML = opt;
				
				var x = $('billing:country_id').getValue();
				if(x=="ID"){
					$('skabkota').setStyle({display:'block'});
					$('skec').setStyle({display:'block'});
					$('billing:city').setValue($('skabkota').getValue());
					$('billing:street2').setValue($('skec').getValue());
					$('billing:city').setStyle({display:'none'});
					$('billing:street2').setStyle({display:'none'});
					}else{
					$('skabkota').setStyle({display:'none'});
					$('skec').setStyle({display:'none'});
					$('billing:city').setValue("");
					$('billing:street2').setValue("");
					$('billing:city').setStyle({display:'block'});
					$('billing:street2').setStyle({display:'block'});
				}
			}
		});
		
		
		var gkk = new GantiKabKota();
		$('billing:region_id').observe('change', gkk.handleChange.bind(gkk));
		$('billing:region_id').observe('click', gkk.handleClick.bind(gkk));
		
		var gkc = new GantiKec();
		$('skabkota').observe('change', gkc.handleChange.bind(gkc));
		$('skec').observe('change', gkc.handleClick.bind(gkc));
		
		
		var gnc = new GantiNegara();
		$('billing:country_id').observe('change',gnc.handleChange.bind(gnc));
		
		
		document.observe("dom:loaded", function() {
			$('billing:city').setValue('');
			var x = $('billing:country_id').getValue();
			if(x=="ID"){
				//$$('dl.shipment-methods')[0].innerHTML = '';
				$('skabkota').setStyle({display:'block'});
				$('skec').setStyle({display:'block'});
				$('billing:city').setStyle({display:'none'});
				$('billing:street2').setStyle({display:'none'});
				
				//var x = $('billing:region_id').getSelectedOptionHTML();
				var x = jq('#billing\\:region_id option:selected').text();
				
				
				new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kabkota/?prop='+x,{
					onSuccess: function(response) {
						// Handle the response content...
						var opt = '';
						response.responseJSON.each(function(item){ 
							opt += '<option value="'+item.nilai+'">'+item.nama+'</option>';
						});
						$('skabkota').innerHTML = opt;
						$('billing:city').setValue($('skabkota').getValue());
						var y = $('skabkota').getValue();
						//var x = $('billing:region_id').getSelectedOptionHTML();
						var x = jq('#billing\\:region_id option:selected').text();
						//alert(x);
						new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kecamatan/?kabkota='+y+'&prop='+x,{
							onSuccess: function(response) {
								// Handle the response content...
								var opt = '';
								response.responseJSON.each(function(item){
									opt += '<option value="'+item+'">'+item+'</option>';
								});
								$('skec').innerHTML = opt;
								$('billing:street2').setValue($('skec').getValue());
								//applyShippingMethod('');
							}
						});
					}
				});
				}else{
				$('skabkota').setStyle({display:'none'});
				$('skec').setStyle({display:'none'});
				$('billing:city').setStyle({display:'block'});
				$('billing:street2').setStyle({display:'block'});
			}
			
			
			
			
			
			$('shipping:city').setValue('');
			var x = $('shipping:country_id').getValue();
			if(x=="ID"){
				$('sskabkota').setStyle({display:'block'});
				$('sskec').setStyle({display:'block'});
				$('shipping:city').setStyle({display:'none'});
				$('shipping:street2').setStyle({display:'none'});
				
				//var x = $('shipping:region_id').getSelectedOptionHTML();
				var x = jq('#shipping\\:region_id option:selected').text();
				new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kabkota/?prop='+x,{
					onSuccess: function(response) {
						var opt = '';
						response.responseJSON.each(function(item){
							opt += '<option value="'+item.nilai+'">'+item.nama+'</option>';
						});
						$('sskabkota').innerHTML = opt;
						$('shipping:city').setValue($('sskabkota').getValue());
						var y = $('sskabkota').getValue();
						//var x = $('shipping:region_id').getSelectedOptionHTML();
						var x = jq('#shipping\\:region_id option:selected').text();
						new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kecamatan/?kabkota='+y+'&prop='+x,{
							onSuccess: function(response) {
								// Handle the response content...
								var opt = '';
								response.responseJSON.each(function(item){
									opt += '<option value="'+item+'">'+item+'</option>';
								});
								$('sskec').innerHTML = opt;
								$('shipping:street2').setValue($('sskec').getValue());
								//syncShipping(true);
							}
						});
					}
				});
				}else{
				$('sskabkota').setStyle({display:'none'});
				$('sskec').setStyle({display:'none'});
				$('shipping:city').setStyle({display:'block'});
				$('shipping:street2').setStyle({display:'block'});
			}
		});
		
		var SamainShipping = Class.create({
			handleChange: function(event) {
				event.stop;
				//$('shipping:street2').setValue($('sskec').getValue());
				//$('shipping:city').setValue($('sskabkota').getValue());
				var x = $('shipping:country_id').getValue();
				if(x=="ID"){
					$('sskabkota').setStyle({display:'block'});
					$('sskec').setStyle({display:'block'});
					$('shipping:city').setValue($('sskabkota').getValue());
					$('shipping:street2').setValue($('sskec').getValue());
					$('shipping:city').setStyle({display:'none'});
					$('shipping:street2').setStyle({display:'none'});
					}else{
					$('sskabkota').setStyle({display:'none'});
					$('sskec').setStyle({display:'none'});
					$('shipping:city').setValue("");
					$('shipping:street2').setValue("");
					$('shipping:city').setStyle({display:'block'});
					$('shipping:street2').setStyle({display:'block'});
				}
			}
		});
		
		var ssh = new SamainShipping();
		$('billing:use_for_shipping_yes').observe('change', ssh.handleChange.bind(ssh));
		
		
		//]]>
	</script>
