<div>	
	<h3><?php echo $this->__('Shipping Address')?></h3>
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select" class="notice"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?></li>
                    <div class="clear"></div>
                    <li class="fields">
                        <div class="fields">
                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('company') ?>"/>
                            </div>
                        </div>
                    </li>
                    <div class="clear"></div>
            <?php $_streetValidationClass = $this->helper('opc')->getAttributeValidationClass('street'); ?>
                    <li class="wide">
                        <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </div>
                    </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

                    <?php if ($this->helper('opc')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="wide">
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                    </li>
                    <li class="wide">
                        <div class="field">
                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="wide">
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('city') ?>" id="shipping:city" style="display:none;" />
																<select id="sskabkota" class="validate-select com-box" >
																	<option>Pilih Kota</option>
																</select>
                            </div>
                        </div>
                    </li>
            <?php //for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
						<?php $_i = 2; ?>
                    <li class="wide">
												<label for="billing:city" class="required"><em>*</em><?php echo $this->__('Kecamatan') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" style="display:none;" />
														<select id="sskec" class="validate-select com-box" >
															<option>Pilih Kecamatan</option>
														</select>
                        </div>
                    </li>
            <?php //endfor; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('opc')->getAttributeValidationClass('postcode') ?>"  />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                            <div class="input-box">
                                <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('opc')->getAttributeValidationClass('fax') ?>" id="shipping:fax"  />
                            </div>
                        </div>
                    </li>
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                	<div class="clear"></div>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
        <li class="control hidden">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </li>
    </ul>

<script type="text/javascript">
//<![CDATA[
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
	

var GantiKecS = Class.create({
	handleClick: function(event) {
		event.stop();
		$('shipping:postcode').setValue("");
		//$$('dl.shipment-methods')[0].innerHTML = '';
		$('shipping:city').setValue($('sskabkota').getValue());
		$('shipping:street2').setValue($('sskec').getValue());
		applyShippingMethod('');
	},
	handleChange: function(event) {
		event.stop();
		opt = '<option value="">Loading...</option>';
		$('sskec').innerHTML = opt;
		var y = $('sskabkota').getValue();
		var x = $('shipping:region_id').getSelectedOptionHTML();
		//alert(x);
		new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kecamatan/?kabkota='+y+'&prop='+x,{
			onLoading: function(response){
				
			},
			onSuccess: function(response) {
				var opt = '';
				response.responseJSON.each(function(item){
					opt += '<option value="'+item+'">'+item+'</option>';
				});
				$('sskec').innerHTML = opt;
				$('shipping:street2').setValue($('sskec').getValue());
				
			}
		});
	}
});


var GantiKabKotaS = Class.create({
	handleClick: function(event) {
		$('shipping:city').setValue($('sskabkota').getValue());
	},
	handleChange: function(event) {
		event.stop();
		opt = '<option value="">Loading...</option>';
		$('sskabkota').innerHTML = opt;
		opt = '<option value="">Loading...</option>';
		$('sskec').innerHTML = opt;
		
		var x = $('shipping:region_id').getSelectedOptionHTML();
		//alert(x);
		new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kabkota/?prop='+x,{
			onLoading: function(response){
				
			},
			onSuccess: function(response) {
				var opt = '';
				response.responseJSON.each(function(item){
					opt += '<option value="'+item.nilai+'">'+item.nama+'</option>';
				});
				$('sskabkota').innerHTML = opt;
				var y = $('sskabkota').getValue();
				var x = $('shipping:region_id').getSelectedOptionHTML();
				
				new Ajax.Request('<?php echo $GLOBALS['panel_url']; ?>api/alamat/kecamatan/?kabkota='+y+'&prop='+x,{
					onSuccess: function(response) {
						var opt = '';
						response.responseJSON.each(function(item){
							opt += '<option value="'+item+'">'+item+'</option>';
						});
						$('sskec').innerHTML = opt;
						
						$('shipping:street2').setValue($('sskec').getValue());
						$('shipping:city').setValue($('sskabkota').getValue());
					}
				});
			}
		});
	}
});
	

var GantiNegaraS = Class.create({
	handleChange: function(event) {
		opt = '<option value="">Loading...</option>';
		$('sskabkota').innerHTML = opt;
		opt = '<option value="">Loading...</option>';
		$('sskec').innerHTML = opt;
		
		var x = $('shipping:country_id').getValue();
		if(x=="ID"){
			$('sskabkota').setStyle({display:'block'});
			$('sskec').setStyle({display:'block'});
			$('shipping:city').setValue($('sskabkota').getValue());
			$('shipping:street2').setValue($('sskec').getValue());
			$('shipping:city').setStyle({display:'none'});
			$('shipping:street2').setStyle({display:'none'});
		}else{
			$('sskabkota').setStyle({display:'none'});
			$('sskec').setStyle({display:'none'});
			$('shipping:city').setValue("");
			$('shipping:street2').setValue("");
			$('shipping:city').setStyle({display:'block'});
			$('shipping:street2').setStyle({display:'block'});
			
		}
	}
});
	
var gkks = new GantiKabKotaS();
$('shipping:region_id').observe('change', gkks.handleChange.bind(gkks));
$('shipping:region_id').observe('click', gkks.handleClick.bind(gkks));

var gkcs = new GantiKecS();
$('sskabkota').observe('change', gkcs.handleChange.bind(gkcs));
$('sskec').observe('change', gkcs.handleClick.bind(gkcs));

var gncs = new GantiNegaraS();
$('shipping:country_id').observe('change',gncs.handleChange.bind(gncs));
//]]>
</script>
</div>