<div id="onestepcheckout-login-popup" style="display:none;">
    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-contents">
            <div id="onestepcheckout-login-popup-contents-forgot" style="display: none;">
                <h1><?php echo $this->__('Forgotten your password?'); ?></h1>
                <p class="title-forgot"><?php echo $this->__('Please enter your email below and we will send you a new password.'); ?></p>
                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
                <form id="onestepcheckout-forgot-form">

                    <div id="onestepcheckout-forgot-loading" style="display: none;" class="loading-ajax-login">&nbsp;
                    </div>
                    <div id="onestepcheckout-forgot-error" class="onestepcheckout-error" style="display: none;">&nbsp;
                    </div>
                    <div id="onestepcheckout-forgot-success" style="display: none;">
                        <!--2014.18.11 update start-->
                        <?php echo $this->__('We have now sent you a new password to your email address.'); ?>
                        <!--2014.18.11 update end-->
                    </div>

                    <ul id="onestepcheckout-forgot-table">

                        <li>
                            <label class="required"
                                   for="id_onestepcheckout_email"><?php echo $this->__('Email address'); ?>
                                <em>*</em></label>
                            <input type="text" class="input-text required-entry validate-email"
                                   name="onestepcheckout_email" id="id_onestepcheckout_email"/>
                        </li>
                        <li class="last">
                            <p><a href="javascript:void(0);"
                                  id="onestepcheckout-return-login-link"><span>&nbsp;</span><?php echo $this->__('Return to login'); ?>
                                </a></p>
                            <button class="button" id="onestepcheckout-forgot-button"
                                    type="button"><?php echo $this->__('Send password'); ?></button>
                        </li>
                    </ul>
                </form>

            </div>

            <div id="onestepcheckout-login-popup-contents-login">

                <h1><?php echo $this->__('Login'); ?></h1>
                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
                <form id="onestepcheckout-login-form">

                    <div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax-login">&nbsp;
                    </div>
                    <div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;
                    </div>

                    <ul id="onestepcheckout-login-table">
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_username"><?php echo $this->__('Email address'); ?>
                                    <em>*</em></label>
                                <input tabindex="100" type="text" class="input-text required-entry validate-email"
                                       name="onestepcheckout_username" id="id_onestepcheckout_username"/>
                            </div>

                        </li>
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_password"><?php echo $this->__('Password'); ?> <em>*</em></label>
                                <input type="password" tabindex="101" name="onestepcheckout_password"
                                       class="input-text required-entry validate-password"
                                       id="id_onestepcheckout_password"/>
                            </div>
                        </li>
                        <li class="last">
                            <button class="button" tabindex="102" id="onestepcheckout-login-button"
                                    type="button"><?php echo $this->__('Login'); ?></button>
                            <p class="forgot-link"><a href="javascript:void(0);"
                                                      id="onestepcheckout-forgot-password-link"><span>&nbsp;</span><?php echo $this->__('Forgotten your password?'); ?>
                                </a></p>
                            <?php if (!Mage::helper('onestepcheckout')->isCustomerLoggedIn() && Mage::helper('onestepcheckout')->enableRegistration()): ?>
                                <p class="register-link"><a href="javascript:void(0);"
                                                            id="onestepcheckout-register-link"><span>&nbsp;</span><?php echo $this->__('Create a new account'); ?>
                                    </a></p>
                            <?php endif; ?>
                        </li>
                    </ul>
                    <!--Leonard SUPEE9767-->
                    <?php echo $this->getBlockHtml('formkey') ?>
                    <!-- Leonard SUPEE 9767-->
                </form>
            </div>
            <!-- Create new account - Add by Leo 03/04/2015 -->
            <div id="onestepcheckout-login-popup-contents-register" style="display: none;">

                <h1><?php echo $this->__('Create New Account'); ?></h1>
                <p class="title-register"><?php echo $this->__('Please enter the following information to create your account.'); ?></p>
                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
                <form id="onestepcheckout-register-form">

                    <div id="onestepcheckout-register-loading" style="display: none;" class="loading-ajax-login">
                        &nbsp;
                    </div>
                    <div id="onestepcheckout-register-error" class="onestepcheckout-error" style="display: none;">
                        &nbsp;
                    </div>

                    <ul id="onestepcheckout-register-table">
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_firstname"><?php echo $this->__('First Name'); ?>
                                    <em>*</em></label>
                                <input tabindex="100" type="text" class="input-text required-entry"
                                       name="onestepcheckout_firstname" id="id_onestepcheckout_firstname"/>
                            </div>

                        </li>
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_lastname"><?php echo $this->__('Last Name'); ?><em>*</em></label>
                                <input tabindex="100" type="text" class="input-text required-entry"
                                       name="onestepcheckout_lastname" id="id_onestepcheckout_lastname"/>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_register_username"><?php echo $this->__('Email address'); ?>
                                    <em>*</em></label>
                                <input tabindex="100" type="text" class="input-text required-entry validate-email"
                                       name="onestepcheckout_register_username"
                                       id="id_onestepcheckout_register_username"/>
                            </div>

                        </li>
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_register_password"><?php echo $this->__('Password'); ?>
                                    <em>*</em></label>
                                <input type="password" tabindex="101" name="onestepcheckout_register_password"
                                       class="input-text required-entry validate-password"
                                       id="id_onestepcheckout_register_password"/>
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                                <label class="required"
                                       for="id_onestepcheckout_register_confirm_password"><?php echo $this->__('Confirm Password'); ?>
                                    <em>*</em></label>
                                <input type="password" tabindex="101" name="onestepcheckout_register_confirm_password"
                                       class="input-text required-entry validate-cpassword"
                                       id="id_onestepcheckout_register_confirm_password"/>
                            </div>
                        </li>
                        <li class="last">
                            <p><a href="javascript:void(0);"
                                  id="onestepcheckout-return-login-link-2"><span>&nbsp;</span><?php echo $this->__('Return to login'); ?>
                                </a></p>
                            <button class="button" tabindex="102" id="onestepcheckout-register-button"
                                    type="button"><?php echo $this->__('Register'); ?></button>
                        </li>
                    </ul>
                </form>
            </div>
            <!-- Create new account - Add by Leo 03/04/2015 -->
        </div>
    </div>

</div>
<script>
    var onestepcheckout_login_popup;
    var login_popup;
    Event.observe(window, 'load', function () {
        var options = {
            forgot_password_url: '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure' => true)); ?>',
            login_url: '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure' => true)); ?>',
            register_url: '<?php echo $this->getUrl('onestepcheckout/ajax/createAcc', array('_secure' => true)); ?>',
            translations: {
                invalid_email: '<?php echo $this->__('Please enter a valid email address'); ?>',
                email_not_found: '<?php echo $this->__('Please enter a registered email address.'); ?>'
            }
        };
        onestepcheckout_login_popup = new OneStepCheckoutLoginPopup(options);
        login_popup = onestepcheckout_login_popup;
    });
</script>

<!-- Terms and conditions -->
<?php $_helper = Mage::helper('onestepcheckout'); ?>
<?php $width = $_helper->getTermPopupWidth() ? $_helper->getTermPopupWidth() : 482; ?>
<?php $height = $_helper->getTermPopupHeight() ? $_helper->getTermPopupHeight() : 530; ?>


<?php if (!$_helper->enableCustomSize()): ?>
    <div id="onestepcheckout-toc-popup" style="display:none;">
        <div class="onestepcheckout-popup-wrapper">
            <div class="onestepcheckout-popup-wrapper-inner">
                <h1><span><?php echo $_helper->getTermTitle(); ?></span></h1>

                <div class="onestepcheckout-toc-terms" style="height: 446px;">
                    <div class="onestepcheckout-toc-terms-content">
                        <?php echo $_helper->getTermsConditionsHtml(); ?>
                    </div>
                </div>

                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
            </div>
        </div>
    </div>
<?php else: ?>
    <div id="onestepcheckout-toc-popup"
         style="display:none; width:<?php echo $width ?>px; height:<?php echo $height ?>px;">
        <div class="onestepcheckout-popup-wrapper2"
             style="width:<?php echo $width ?>px; height:<?php echo $height ?>px;">
            <div class="onestepcheckout-popup-wrapper-inner2">
                <h1><span><?php echo $_helper->getTermTitle(); ?></span></h1>

                <div class="onestepcheckout-toc-terms" style="<?php
                if ($height) {
                    $height = (int)$height - 87;
                    echo 'height: ' . ((int)$height) . 'px;';
                } else {
                    echo 'height: 446px;';
                }
                ?>">
                    <div class="onestepcheckout-toc-terms-content">
                        <?php echo $_helper->getTermsConditionsHtml(); ?>
                    </div>
                </div>

                <p class="close"><a href="javascript:void(0);"><?php echo $this->__('X'); ?></a></p>
            </div>
        </div>

    </div>
<?php endif; ?>